name: alwazirchat
description: "A new Flutter chat application."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '^3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # الاتصال والمحادثة الفورية
  socket_io_client: ^2.0.3+1
  http: ^1.2.0

  # إدارة الحالة (State Management)
  provider: ^6.1.1

  # الوسائط والملفات (صور، صوت، مستندات)
  image_picker: ^1.0.7
  file_picker: ^8.0.0
  audioplayers: ^6.0.0
  record: ^5.1.0

  # التخزين المحلي (Local Storage)
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # الإشعارات وتحسين الأداء والتنسيق
  flutter_local_notifications: ^17.0.0
  intl: ^0.19.0
  cached_network_image: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  dependencies:
  flutter_localizations:
    sdk: flutter


flutter:
  uses-material-design: true
